databases:
  - name: CodeOverflow
    databaseName: codeoverflow
    user: codeoverflow_user

services:
  - type: web
    name: CodeOverflow
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: CodeOverflow
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false